name: Use Setup-Miniconda From Marketplace To Run Tests
on: [push]

jobs:
  miniconda:
    name: Miniconda
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Run tests
        shell: bash -l {0}
        run: |
          conda install pdal
          python -m pip install --upgrade pip
          pip install dask distributed pdal
          python src/test.py