name: Unit Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          sudo apt -y install pdal
          python -m pip install --upgrade pip
          pip install dask distributed
      - name: Run tests
        run: |
          python src/test.py